"""Emit generated content modules. All emitters return python source text."""
import pprint

HEADER = "# GENERATED by tools/kbk_import — do not hand-edit.\n"

# constants the engine needs at runtime (loader math + level bounds)
RUNTIME_CONSTANTS = ["MAX_LEVEL", "LEVEL_HERO", "LEVEL_IMMORTAL", "WEIGHT_STANDARD",
                     "AC_PER_ONE_PERCENT_DECREASE_DAMAGE", "MAX_STATS"]


def _fmt(name, obj):
    return f"{name} = {pprint.pformat(obj, width=100, sort_dicts=False)}\n"


def emit_constants(defines):
    from tools.kbk_import.resolve import Resolver
    r = Resolver(defines)
    body = "".join(f"{n} = {r.num(n)}\n" for n in RUNTIME_CONSTANTS if n in defines)
    return HEADER + body


def emit_classes(entries, r):
    classes, order = {}, []
    for e in entries:
        name = r.value(e[0])
        order.append(name)
        classes[name] = {
            "name": name,
            "who_name": r.value(e[1]),
            "align": r.num(e[2]),
            "xpadd": r.num(e[3]),
            "weapon": r.num(e[4]),
            "guild_rooms": [r.num(v) for v in e[5]],
            "skill_adept": r.num(e[6]),
            "thac0_00": r.num(e[7]),
            "thac0_32": r.num(e[8]),
            "hp_min": r.num(e[9]),
            "hp_max": r.num(e[10]),
            "f_mana": r.value(e[11]),
            "base_group": r.value(e[12]),
            "default_group": r.value(e[13]),
            "ctype": r.num(e[14]),
        }
    return HEADER + _fmt("CLASSES", classes) + _fmt("CLASS_ORDER", order), order


def _per_class(values, r, order):
    return {cls: r.num(values[i]) if i < len(values) else 0 for i, cls in enumerate(order)}


def emit_skills(entries, r, class_order):
    skills = {}
    for e in entries:
        name = r.value(e[0])
        if not name or name == "reserved":
            continue
        if name in skills:
            continue  # duplicate names: C skill_lookup returns the first match
        skills[name] = {
            "name": name,
            "skill_level": _per_class(e[1], r, class_order),
            "rating": _per_class(e[2], r, class_order),
            "spell_fun": r.spell_name(e[3]),
            "target": r.num(e[4]),
            "minimum_position": r.num(e[5]),
            "pgsn": r.gsn_name(e[6]),
            "slot": r.slot(e[7]),
            "min_mana": r.num(e[8]),
            "beats": r.num(e[9]),
            "noun_damage": r.value(e[10]),
            "msg_off": r.value(e[11]),
            "msg_obj": r.value(e[12]) if len(e) > 12 else "",
            "ctype": r.num(e[13]) if len(e) > 13 else 0,
        }
    return HEADER + _fmt("SKILLS", skills)


def emit_groups(entries, r, class_order):
    groups = {}
    for e in entries:
        name = r.value(e[0])
        if not name or name == "reserved":
            continue
        groups[name] = {
            "name": name,
            "rating": _per_class(e[1], r, class_order),
            "spells": [r.value(s) for s in e[2] if r.value(s)],
        }
    return HEADER + _fmt("GROUPS", groups)


def emit_races(race_entries, pc_entries, r, class_order):
    races = {}
    for e in race_entries:
        # Skip NULL terminator entries
        if not e or str(e[0]) == "NULL":
            continue
        name = r.value(e[0])
        races[name] = {"name": name, "pc_race": r.value(e[1]) if len(e) > 1 else False,
                       "act": r.num(e[2]) if len(e) > 2 else 0, "aff": r.num(e[3]) if len(e) > 3 else 0,
                       "off": r.num(e[4]) if len(e) > 4 else 0,
                       "imm": r.num(e[5]) if len(e) > 5 else 0, "res": r.num(e[6]) if len(e) > 6 else 0,
                       "vuln": r.num(e[7]) if len(e) > 7 else 0,
                       "form": r.num(e[8]) if len(e) > 8 else 0, "parts": r.num(e[9]) if len(e) > 9 else 0}
    pc_races = {}
    for e in pc_entries:
        name = r.value(e[0])
        if name.startswith("null"):
            continue
        pc_races[name] = {
            "name": name,
            "who_name": r.value(e[1]).strip() if len(e) > 1 else "",
            "align": r.num(e[2]) if len(e) > 2 else 0,
            "xpadd": r.num(e[3]) if len(e) > 3 else 0,
            "skills": [r.value(s) for s in (e[4] if len(e) > 4 else []) if r.value(s)],
            "classes": {cls: bool(r.num(e[5][i])) if len(e) > 5 and i < len(e[5]) else False
                        for i, cls in enumerate(class_order)},
            "stats": [r.num(v) for v in (e[6] if len(e) > 6 else [])] if len(e) > 6 else [],
            "max_stats": [r.num(v) for v in (e[7] if len(e) > 7 else [])] if len(e) > 7 else [],
            "size": r.num(e[8]) if len(e) > 8 else 0,
            "set_race": r.value(e[9]) if len(e) > 9 else False,
        }
    return HEADER + _fmt("RACES", races) + _fmt("PC_RACES", pc_races)


def emit_materials(text: str) -> str:
    lines = iter(text.splitlines())
    for line in lines:
        if line.split() and line.split()[0] == "MATS":
            break
    materials = {}
    for line in lines:
        line = line.strip()
        if not line or "~" not in line:
            continue
        name, rest = line.split("~", 1)
        name = name.strip()
        nums = [int(x) for x in rest.split()[:5]]
        materials[name] = {"name": name,
                           **dict(zip(("prot_pierce", "prot_bash", "prot_slash",
                                       "prot_magic", "relative_weight"), nums))}
    return HEADER + _fmt("MATERIALS", materials)


def _str(token):
    return token[1] if isinstance(token, tuple) and token[0] == "str" else str(token)


def emit_titles(entries, class_order):
    titles = {}
    for i, cls in enumerate(class_order):
        if i >= len(entries):
            break
        titles[cls] = [[_str(pair[0]), _str(pair[1])] for pair in entries[i]]
    return HEADER + _fmt("TITLES", titles)
