"""Emit generated content modules. All emitters return python source text."""
import pprint

HEADER = "# GENERATED by tools/kbk_import — do not hand-edit.\n"

# constants the engine needs at runtime (loader math + level bounds)
RUNTIME_CONSTANTS = ["MAX_LEVEL", "LEVEL_HERO", "LEVEL_IMMORTAL", "WEIGHT_STANDARD",
                     "AC_PER_ONE_PERCENT_DECREASE_DAMAGE", "MAX_STATS"]


def _fmt(name, obj):
    return f"{name} = {pprint.pformat(obj, width=100, sort_dicts=False)}\n"


def emit_constants(defines):
    from tools.kbk_import.resolve import Resolver
    r = Resolver(defines)
    body = "".join(f"{n} = {r.num(n)}\n" for n in RUNTIME_CONSTANTS if n in defines)
    return HEADER + body


def emit_classes(entries, r):
    classes, order = {}, []
    for e in entries:
        name = r.value(e[0])
        order.append(name)
        classes[name] = {
            "name": name,
            "who_name": r.value(e[1]),
            "align": r.num(e[2]),
            "xpadd": r.num(e[3]),
            "weapon": r.num(e[4]),
            "guild_rooms": [r.num(v) for v in e[5]],
            "skill_adept": r.num(e[6]),
            "thac0_00": r.num(e[7]),
            "thac0_32": r.num(e[8]),
            "hp_min": r.num(e[9]),
            "hp_max": r.num(e[10]),
            "f_mana": r.value(e[11]),
            "base_group": r.value(e[12]),
            "default_group": r.value(e[13]),
            "ctype": r.num(e[14]),
        }
    return HEADER + _fmt("CLASSES", classes) + _fmt("CLASS_ORDER", order), order


def _per_class(values, r, order):
    return {order[i]: r.num(v) for i, v in enumerate(values) if i < len(order)}


def emit_skills(entries, r, class_order):
    skills = {}
    for e in entries:
        name = r.value(e[0])
        if not name or name == "reserved":
            continue
        skills[name] = {
            "name": name,
            "skill_level": _per_class(e[1], r, class_order),
            "rating": _per_class(e[2], r, class_order),
            "spell_fun": r.spell_name(e[3]),
            "target": r.num(e[4]),
            "minimum_position": r.num(e[5]),
            "pgsn": r.gsn_name(e[6]),
            "slot": r.slot(e[7]),
            "min_mana": r.num(e[8]),
            "beats": r.num(e[9]),
            "noun_damage": r.value(e[10]),
            "msg_off": r.value(e[11]),
            "msg_obj": r.value(e[12]),
            "ctype": r.num(e[13]),
        }
    return HEADER + _fmt("SKILLS", skills)


def emit_groups(entries, r, class_order):
    groups = {}
    for e in entries:
        name = r.value(e[0])
        if not name:
            continue
        groups[name] = {
            "name": name,
            "rating": _per_class(e[1], r, class_order),
            "spells": [r.value(s) for s in e[2] if r.value(s)],
        }
    return HEADER + _fmt("GROUPS", groups)
