"""Emit generated content modules. All emitters return python source text."""
import pprint

HEADER = "# GENERATED by tools/kbk_import — do not hand-edit.\n"

# constants the engine needs at runtime (loader math + level bounds)
RUNTIME_CONSTANTS = ["MAX_LEVEL", "LEVEL_HERO", "LEVEL_IMMORTAL", "WEIGHT_STANDARD",
                     "AC_PER_ONE_PERCENT_DECREASE_DAMAGE", "MAX_STATS"]


def _fmt(name, obj):
    return f"{name} = {pprint.pformat(obj, width=100, sort_dicts=False)}\n"


def emit_constants(defines):
    from tools.kbk_import.resolve import Resolver
    r = Resolver(defines)
    body = "".join(f"{n} = {r.num(n)}\n" for n in RUNTIME_CONSTANTS if n in defines)
    return HEADER + body


def emit_classes(entries, r):
    classes, order = {}, []
    for e in entries:
        name = r.value(e[0])
        order.append(name)
        classes[name] = {
            "name": name,
            "who_name": r.value(e[1]),
            "align": r.num(e[2]),
            "xpadd": r.num(e[3]),
            "weapon": r.num(e[4]),
            "guild_rooms": [r.num(v) for v in e[5]],
            "skill_adept": r.num(e[6]),
            "thac0_00": r.num(e[7]),
            "thac0_32": r.num(e[8]),
            "hp_min": r.num(e[9]),
            "hp_max": r.num(e[10]),
            "f_mana": r.value(e[11]),
            "base_group": r.value(e[12]),
            "default_group": r.value(e[13]),
            "ctype": r.num(e[14]),
        }
    return HEADER + _fmt("CLASSES", classes) + _fmt("CLASS_ORDER", order), order
